---
stages:
  - build
  - test
  - cleanup
  - push
  - deploy

# сбилдим проект
build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID .
# проверим, что сборка запускается
test:
  stage: test
  image:
    name: docker/compose:1.26.2
    entrypoint: [""]
  script:
    - docker-compose 
        -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID"
      up
        --abort-on-container-exit
        --exit-code-from app
        --quiet-pull
# остановим тестовую сборку, выполняется всегда (always), не зависимо от предыудщих,
# обычно если джоба завершилась неудачей, то следующие не будут запущены
cleanup:
  stage: cleanup
  image:
    name: docker/compose:1.23.2
    entrypoint: [""]
  script:
    - docker-compose -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID" down
  when: always
# иногда делают билд и пуш в одной джобе, но тут мы его вынесли в отдельную джобу
# Сначала мы логинимся в REGISTRY, а затем пушим с помощью CI_BUILD_TOKEN, который генерится для
# конкретной джобы, т.е. после завершения джобы он становится не валидным
# и только для ветки мастер
push:
  stage: push
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  only:
    - master
# и сам деплой, это одни из распространенных методов
# сначала выполним предварительные щаги
# лучше вынести секретные переменные типа DB_PASSWORD в gitLab variables
# SECRET_KEY_BASE не надо менять
deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PRODUCTION_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@"$PRODUCTION_SERVER_IP" "echo $CI_BUILD_TOKEN | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY};
      docker stop xpaste-app; docker rm xpaste-app;
      docker run --name xpaste-app --network xpaste-net
      -e DB_HOST=xpaste-postgres
      -e DB_PORT=5432
      -e DB_NAME=xpaste
      -e DB_USER=postgres
      -e DB_PASSWORD=postgres
      -e RAILS_ENV=production
      -e RAILS_LOG_TO_STDOUT=1
      -e SECRET_KEY_BASE=xxxxxxxxxxxxxxxxxxxxxxxxx
      -p 80:80
      -d $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID"
  only:
    - master
...
